### ISSUE TITLE
Broken link in "Circumambient Syntax" post 

### ISSUE THREAD

**Issue by laszabine** [outde-xyz/website#29]
In [content/Discussions/2019-11-11_graf_circumambient_syntax.md](https://github.com/outde-xyz/website/blob/master/content/Discussions/2019-11-11_graf_circumambient_syntax.md), line 172, the link for tree 3 points to a non-existing file `{filename}/img/thomas/movement_toneplateauing/dep_partial.svg`. It should instead point to [`{filename}/img/thomas/movement_toneplateauing/dep_partialagree.svg`](https://github.com/outde-xyz/website/blob/master/content/img/thomas/movement_toneplateauing/dep_partialagree.svg).

**Comment by thomas--graf** [comment]
fixed, thx
