### ISSUE TITLE
Best comment implementation

### ISSUE THREAD

**Issue by thomas--graf** [outde-xyz/website#5]
Here's the options I'm aware of, with some pros and cons:

1. *Disqus*: [+free, +spam_protection, +easy setup, +instantaneous update, -markdown, -pandoc -math, -privacy, -archiveable, -portable, -open source]
1. *Discourse*: [-free, +spam_protection, -easy setup, +instantaneous update, +markdown, -pandoc, +math (with plugin), +privacy, -portable, ?open source]
1. *Github*: [+free, +spam_protection, +easy setup, +instantaneous update, +markdown, -pandoc, -math, +privacy, +portable]
1. *Staticman*: [+free, -spam_protection, -easy setup, -instantaneous update, +markdown, +pandoc, +math, +privacy, +portable]

I think it's a draw between github and staticman:

- With staticman, all comments are collected and typeset by Pelican. This means that everything that works in articles also works in comments. But obviously the process takes longer (at least a few seconds), and commenters have to refresh after submitting a comment. If we moderate comments to filter out spam, it would take even longer. Long turnaround is detrimental to lively discussion.

- With github, we have a very convenient flow. But everybody needs a github account to comment, and there is no MathJAX support. If there's a strong need for math, that would hamper the quality of discussion. But users can install webextensions in their browser as a workaround. It's also annoying that users need to give *utterances* account access in order to post from the blog rather than through github issues.

**Comment by thomas--graf** [comment]
Forgot that github also provides easy update notifications via email. With staticman, this requires extra setup.

**Comment by thomas--graf** [comment]
One more for github: comments can be edited.

**Comment by thomas--graf** [comment]
One more option: Pelican's static comment system via email. It's similar to staticman, but easier to set up.

Basically, the comment form submits the comment as an email, the content of which must be put in a separate comments folder of the Pelican project. When the site is regenerated, the comment is inserted into the page and processed like any other content.

Let's check the parameters:

- +free
- +spam_protection: We can set up a bash script that only processes messages from pre-approved email addresses. After somebody has been approved, they can post from that address without any login, reCAPTCHAs and all that crud. Of course that opens up the door for posting under a different name, but is this seriously a risk for an academic blog? If so, we could expand the script to use a hashed and salted passphrase.
- ~easy setup: Since it's email it's not too hard, but we need to set up the infrastructure for automatically reading emails from approved addresses, putting them in the right folder, and triggering a rebuild of the website.
- -instantaneous: This might be the slowest option. First we have to wait for the email to arrive, process it, and trigger a rebuild. With a large site, the rebuild can take a while (minutes on a slow build server).
- +markdown, +pandoc, +math: Yep, that all comes for free since comments are just part of the compiled articles
- +privacy: yes, we only store preapproved emails and perhaps passwords
- +portable: yes, it's all part of the same git repository
- +notifications: We can have an RSS feed for each article, and we could also email update notifications to anybody who has commented (they had to provide an email address, after all).
- +editable: tricky, but doable; in principle, there could be an edit button that allows sending out a modified message, and if the edit comes from the same address as the original message, we replace the latter by the former; we probably should enforce a time limit of 24h, though, I'm not a big fan of major edits way after the fact.

**Comment by heinz-jeffrey** [comment]
Thanks for the exhaustive search for options. In the end, I think github offers the best options overall. The only downside is math in comments - but as you point out that seems addressable on the user side with browser extensions. So verifying that is the case, followed by giving folks some options for for typical browsers seems like logical next steps. 

Wish I had some time to spend on this... You're doing a great job!

**Comment by thomas--graf** [comment]
Just for shits and giggles I've created a separate branch with the email-based submission system. The layout is still a little wonky because I can never wrap my head around `div`-positioning with CSS, but it works in the sense that comments get sent out as emails. The next step would be to incorporate it into an automatic build system. That will take time, so I agree that github is the winner for now by virtue of actually being ready to use.

**Comment by thomas--graf** [comment]
Another oversight: those plugins only work directly on Github. So comments that get loaded directly on the blog still don't have math. I'm starting to really prefer the email solution, provided I can get it to work.

**Comment by thomas--graf** [comment]
We went with talkyard.
